[package]
name = "passwordgen"
authors = ["Ty Wagner <tywagner04@gmail.com>"]
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
path = "src/passwordgen.rs"

[dependencies]
rand = "0.9.2"
